# Generated by Django 4.2.5 on 2023-09-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='News image', null=True, upload_to='info_service/')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
