# Generated by Django 4.2.5 on 2023-09-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='News image', null=True, upload_to='info_service/news'),
        ),
    ]
