# Generated by Django 4.2.5 on 2023-09-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
