# Generated by Django 4.2.5 on 2023-09-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0003_alter_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
