# Generated by Django 4.2.5 on 2023-09-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0004_news_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(editable=False, unique=True)),
                ('expiration_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
