# Generated by Django 4.2.5 on 2023-09-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0005_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
