# Generated by Django 4.2.5 on 2023-09-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0006_promocode_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
