# Generated by Django 4.2.5 on 2023-09-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0008_alter_promocode_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
