# Generated by Django 4.2.5 on 2023-09-12 08:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repair_service', '0001_initial'),
        ('info_service', '0009_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('reviewer_name', models.CharField(max_length=30)),
                ('used_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='repair_service.service')),
                ('text', models.CharField(max_length=256)),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
