# Generated by Django 4.2.5 on 2023-09-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0009_vacancy_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='reviewer_name',
            new_name='reviewer',
        ),
    ]
