# Generated by Django 4.2.5 on 2023-09-12 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repair_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_service', '0009_vacancy_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='used_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repair_service.service'),
        ),
    ]
