# Generated by Django 4.2.5 on 2023-09-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0011_alter_feedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
