# Generated by Django 4.2.5 on 2023-09-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0011_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, help_text='Worker image', null=True, upload_to='info_service/'),
        ),
    ]
